kytitle: "Valérie Plusquellec"
logo:  img/vp.jpeg
description: "Créative, rigoureuse, et pédagogue, je suis passionée par la résolution de problèmes."
show_downloads: false
theme: jekyll-theme-minimal
lang: fr

