kytitle: "Valérie Plusquellec"
logo:  img/vp.jpeg
description: "Créative, rigoureuse, et pédagogue, j’aspire à mettre les mathématiques appliquées et l’analyse de données au service des missions qui me seront confiées."
show_downloads: false
theme: jekyll-theme-minimal
lang: fr

